- name: Install Software Properties Common
  apt:
    name: software-properties-common
    state: present
    update_cache: yes

- name: Add Ansible PPA
  ansible.builtin.apt_repository:
    repo: ppa:ansible/ansible
    state: present
    update_cache: yes

- name: Install Ansible
  apt:
    name: ansible
    state: present
    update_cache: yes
