- name: Ensure curl is installed
  apt:
    name: curl
    state: present

- name: Install k3d (latest)
  get_url:
    url: https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh
    dest: /tmp/k3d-install.sh
    mode: '0755'

- name: Run k3d installer
  command: /tmp/k3d-install.sh
  args:
    creates: /usr/local/bin/k3d