- name: Install KVM and dependencies
  apt:
    name:
      - qemu-kvm
      - virt-manager
      - libvirt-daemon-system
      - virtinst
      - libvirt-clients
      - bridge-utils
      - cloud-image-utils
      - virtinst
      - libguestfs-tools
      - python3-lxml
      - python3-libvirt
    state: present
    update_cache: yes

- name: Ensure libvirtd service is enabled and running
  systemd:
    name: libvirtd
    enabled: true
    state: started

- name: Add user to kvm group
  user:
    name: "{{ user_name }}"
    groups: kvm
    append: yes

- name: Add user to libvirt group
  user:
    name: "{{ user_name }}"
    groups: libvirt
    append: yes

- name: Ensure libvirt default network is stopped and disabled
  community.libvirt.virt_net:
    name: default
    state: absent
    autostart: no

- name: Define libvirt bridge network
  community.libvirt.virt_net:
    name: br0-net
    state: present
    autostart: yes
    xml: |
      <network>
        <name>br0-net</name>
        <forward mode='bridge'/>
        <bridge name='br0'/>
      </network>
