---
- name: Create mount directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /var/lib/docker
    - /bkp-ssd
    - /usb/apollo
    - /rclone/gdrive
    - /download
    - /bkp

- name: Create docker logical volume
  community.general.lvol:
    vg: ubuntu-vg
    lv: docker-lv
    size: 35.42g
    state: present

- name: Create XFS filesystem for docker LV
  filesystem:
    fstype: xfs
    dev: /dev/ubuntu-vg/docker-lv

- name: Mount docker LV
  mount:
    path: /var/lib/docker
    src: /dev/ubuntu-vg/docker-lv
    fstype: xfs
    opts: defaults
    state: mounted

- name: Create bkp-ssd logical volume
  community.general.lvol:
    vg: ubuntu-vg
    lv: bkpssd-lv
    size: 20g
    state: present

- name: Create XFS filesystem for bkp LV
  filesystem:
    fstype: xfs
    dev: /dev/ubuntu-vg/bkpssd-lv

- name: Mount bkp LV
  mount:
    path: /bkp-ssd
    src: /dev/ubuntu-vg/bkpssd-lv
    fstype: xfs
    opts: defaults
    state: mounted

- name: Mount usb/apollo
  mount:
    path: /usb/apollo
    src: /dev/sdc1
    fstype: xfs
    opts: defaults,nofail
    state: mounted

- name: Set hdparm standby timeout
  command: hdparm -S 15 /dev/sdc
  changed_when: false

- name: Create download LV
  community.general.lvol:
    vg: hdd-vg
    lv: download-lv
    size: 150G
    state: present

- name: Create ext4 filesystem for download LV
  filesystem:
    fstype: ext4
    dev: /dev/hdd-vg/download-lv

- name: Mount download LV
  mount:
    path: /download
    src: /dev/hdd-vg/download-lv
    fstype: ext4
    opts: defaults
    state: mounted

- name: Create bkp LV
  community.general.lvol:
    vg: hdd-vg
    lv: bkp-lv
    size: 210G
    state: present

- name: Create ext4 filesystem for bkp LV
  filesystem:
    fstype: ext4
    dev: /dev/hdd-vg/bkp-lv

- name: Mount bkp LV
  mount:
    path: /bkp
    src: /dev/hdd-vg/bkp-lv
    fstype: ext4
    opts: defaults
    state: mounted

- name: Create timemachine directory
  file:
    path: /bkp/docker/timemachine
    state: directory

- name: Create timemachine LV
  community.general.lvol:
    vg: hdd-vg
    lv: timemachine-lv
    size: 250G
    state: present

- name: Create ext4 filesystem for timemachine LV
  filesystem:
    fstype: ext4
    dev: /dev/hdd-vg/timemachine-lv

- name: Mount timemachine LV
  mount:
    path: /bkp/docker/timemachine
    src: /dev/hdd-vg/timemachine-lv
    fstype: ext4
    opts: defaults
    state: mounted