- name: Ensure playbook runs as root
  assert:
    that: ansible_user_id == "root"
    fail_msg: "Please run as root"

- name: Install root crontab
  copy:
    src: crontab
    dest: /root/crontab.tmp
    mode: '0644'
  notify: Install root crontab

- name: Apply root crontab if updated
  shell: crontab /root/crontab.tmp -u root