---
- name: Install node exporter
  ansible.builtin.include_role:
    name: prometheus.prometheus.node_exporter

- name: Install smartctl exporter
  ansible.builtin.include_role:
    name: prometheus.prometheus.smartctl_exporter

- name: Ensure override directory for smartctl_exporter exists
  ansible.builtin.file:
    path: /etc/systemd/system/smartctl_exporter.service.d
    state: directory
    mode: '0755'

- name: Ensure smartctl_exporter runs as root
  ansible.builtin.copy:
    dest: /etc/systemd/system/smartctl_exporter.service.d/override.conf
    content: |
      [Service]
      User=root
      Group=root
  notify: Restart smartctl_exporter